version: "3.9"

services:
  metube:
    build: .
    container_name: metube
    restart: unless-stopped

    volumes:
      - /root/volumes/metube/downloads:/downloads

    environment:
      - PUID=1000
      - PGID=1000

    networks:
      - traefik

    healthcheck:
      disable: true

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.metube.rule=Host(`metube.ecotron.co.in`)"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.tls.certresolver=myresolver"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"

networks:
  traefik:
    external: true